name: Build and Release Windows EXE

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Compile Inno Setup Installer
        run: |
          iscc nfcapp.iss

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nfc-passport-reader-installer
          path: build/windows/nfc_passport_reader.exe
